services:
  - type: web
    name: tds-virtual-ta
    env: python
    pythonVersion: 3.13
    region: oregon
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api && gunicorn app:app --workers=1
    workingDir: api
    plan: free